config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'static_pages#landing'

  resources :properties, only: [:index, :show]
  resources :messages, only: [:new, :create]

  get 'landing', to: 'static_pages#landing'
  
end

app/views/shared/_footer.haml
%footer.footer-container
  %section.footer-primary
    .container
      .row
        .col-sm-6.col-md-3
          %h3 Footer Component
          %p Choose from our favourite tags:
          %ul.tags
            %li
              %a{:href => "#link"} design
            %li
              %a{:href => "#link"} layout
            %li
              %a{:href => "#link"} stack
            %li
              %a{:href => "#link"} PSD
            %li
              %a{:href => "#link"} bootstrap
            %li
              %a{:href => "#link"} menu
            %li
              %a{:href => "#link"} type
            %li
              %a{:href => "#link"} paper
            %li
              %a{:href => "#link"} press
        .col-sm-6.col-md-3
          %h3 Image Stream List
          %p View our latest stills in Flicker:
          %ul.img-stream
            %li
              %a{:href => "#link"}
                %img.media-object{:alt => "img", "data-src" => "holder.js/55x55"}/
            %li
              %a{:href => "#link"}
                %img.media-object{:alt => "img", "data-src" => "holder.js/55x55"}/
            %li
              %a{:href => "#link"}
                %img.media-object{:alt => "img", "data-src" => "holder.js/55x55"}/
            %li
              %a{:href => "#link"}
                %img.media-object{:alt => "img", "data-src" => "holder.js/55x55"}/
            %li
              %a{:href => "#link"}
                %img.media-object{:alt => "img", "data-src" => "holder.js/55x55"}/
            %li
              %a{:href => "#link"}
                %img.media-object{:alt => "img", "data-src" => "holder.js/55x55"}/
            %li
              %a{:href => "#link"}
                %img.media-object{:alt => "img", "data-src" => "holder.js/55x55"}/
            %li
              %a{:href => "#link"}
                %img.media-object{:alt => "img", "data-src" => "holder.js/55x55"}/
        .col-sm-6.col-md-3
          %h3 Hyperlinks List
          %p Contact us whenever you want:
          %ul.list-unstyled
            %li
              %i.fa.fa-angle-right
              %a{:href => "#link"} 9am-6pm ET Mon-Fri
            %li
              %i.fa.fa-angle-right
              %a{:href => "#link"} US (877) 977-8732
            %li
              %i.fa.fa-angle-right
              %a{:href => "#link"} International +1 646 490 1679
        .col-sm-6.col-md-3
          %h3 Social Media List
          %p Stick to the social media hype:
          %ul.social-networks
            %li
              %a.btn.btn-twitter{:href => "#"}
                %i.fa.fa-fw.fa-twitter
            %li
              %a.btn.btn-facebook{:href => "#"}
                %i.fa.fa-fw.fa-facebook
            %li
              %a.btn.btn-google-plus{:href => "#"}
                %i.fa.fa-fw.fa-google-plus
            %li
              %a.btn.btn-pinterest{:href => "#"}
                %i.fa.fa-fw.fa-pinterest
          %p We are friendly. Give us a ding!
  %section.footer-secondary
    .container
      .row
        .col-lg-12
          %p.no-margin-bottom
            All Rights Reserved ® Designed by
            %a{:href => "http://twitter.com/graphikaria", :target => "_blank"} @Graphikaria

app/views/shared/_footer.html.haml
%footer.footer-container
  %section.footer-primary
    .container
      .row
        .col-sm-6.col-md-3
          %h3 Footer Component
          %p Choose from our favourite tags:
          %ul.tags
            %li
              %a{:href => "#link"} design
            %li
              %a{:href => "#link"} layout
            %li
              %a{:href => "#link"} stack
            %li
              %a{:href => "#link"} PSD
            %li
              %a{:href => "#link"} bootstrap
            %li
              %a{:href => "#link"} menu
            %li
              %a{:href => "#link"} type
            %li
              %a{:href => "#link"} paper
            %li
              %a{:href => "#link"} press
        .col-sm-6.col-md-3
          %h3 Image Stream List
          %p View our latest stills in Flicker:
          %ul.img-stream
            %li
              %a{:href => "#link"}
                %img.media-object{:alt => "img", "data-src" => "holder.js/55x55"}/
            %li
              %a{:href => "#link"}
                %img.media-object{:alt => "img", "data-src" => "holder.js/55x55"}/
            %li
              %a{:href => "#link"}
                %img.media-object{:alt => "img", "data-src" => "holder.js/55x55"}/
            %li
              %a{:href => "#link"}
                %img.media-object{:alt => "img", "data-src" => "holder.js/55x55"}/
            %li
              %a{:href => "#link"}
                %img.media-object{:alt => "img", "data-src" => "holder.js/55x55"}/
            %li
              %a{:href => "#link"}
                %img.media-object{:alt => "img", "data-src" => "holder.js/55x55"}/
            %li
              %a{:href => "#link"}
                %img.media-object{:alt => "img", "data-src" => "holder.js/55x55"}/
            %li
              %a{:href => "#link"}
                %img.media-object{:alt => "img", "data-src" => "holder.js/55x55"}/
        .col-sm-6.col-md-3
          %h3 Hyperlinks List
          %p Contact us whenever you want:
          %ul.list-unstyled
            %li
              %i.fa.fa-angle-right
              %a{:href => "#link"} 9am-6pm ET Mon-Fri
            %li
              %i.fa.fa-angle-right
              %a{:href => "#link"} US (877) 977-8732
            %li
              %i.fa.fa-angle-right
              %a{:href => "#link"} International +1 646 490 1679
        .col-sm-6.col-md-3
          %h3 Social Media List
          %p Stick to the social media hype:
          %ul.social-networks
            %li
              %a.btn.btn-twitter{:href => "#"}
                %i.fa.fa-fw.fa-twitter
            %li
              %a.btn.btn-facebook{:href => "#"}
                %i.fa.fa-fw.fa-facebook
            %li
              %a.btn.btn-google-plus{:href => "#"}
                %i.fa.fa-fw.fa-google-plus
            %li
              %a.btn.btn-pinterest{:href => "#"}
                %i.fa.fa-fw.fa-pinterest
          %p We are friendly. Give us a ding!
  %section.footer-secondary
    .container
      .row
        .col-lg-12
          %p.no-margin-bottom
            All Rights Reserved ® Designed by
            %a{:href => "http://twitter.com/graphikaria", :target => "_blank"} @Graphikaria

app/views/shared/_header.haml
/ Main Navbar
%nav.navbar.navbar-default.navbar-static-top.header{ role: :navigation }
  .container
    .row.clearfix
      .col-md-3.col-sm-3
        %button.navbar-toggle{ 'data-target' => '.navbar-main-collapse', 'data-toggle' => 'collapse', type: :button }
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        .navbar-header
          = link_to image_tag('logo-dark.png'), root_path, class: 'navbar-brand'
      .col-md-6.col-sm-6
        / Navbar
        .collapse.navbar-collapse.navbar-main-collapse
          %ul.nav.navbar-nav
            %li
              = link_to 'Principal', root_path, class: ('active-button' if current_page? root_path)
            %li
              = link_to 'Propiedades', properties_path, class: ('active-button' if current_page? properties_path)
            %li
              = link_to 'Contacto', new_message_path, class: ('active-button' if current_page? new_message_path)
      .col-md-3.col-sm-3.numbers
        .phone 2696 74 12
        .phone 099 281 543

app/views/shared/_header.html.haml
/ Main Navbar
%nav.navbar.navbar-default.navbar-static-top.header{ role: :navigation }
  .container
    .row.clearfix
      .col-md-3.col-sm-3
        %button.navbar-toggle{ 'data-target' => '.navbar-main-collapse', 'data-toggle' => 'collapse', type: :button }
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        .navbar-header
          = link_to image_tag('logo-dark.png'), root_path, class: 'navbar-brand'
      .col-md-6.col-sm-6
        / Navbar
        .collapse.navbar-collapse.navbar-main-collapse
          %ul.nav.navbar-nav
            %li
              = link_to 'Principal', root_path, class: ('active-button' if current_page? root_path)
            %li
              = link_to 'Propiedades', properties_path, class: ('active-button' if current_page? properties_path)
            %li
              = link_to 'Contacto', root_path
      .col-md-3.col-sm-3.numbers
        .phone 2696 74 12
        .phone 099 281 543

app/views/shared/_search.haml
/ <form action=' class='form-inline'>
= form_tag properties_path, :method => 'get' do
  .row
    .col-md-3
      = label_tag 'Tipo de Propiedad'
      = select_tag 'search[property_type]', grouped_options_for_select(@property_types, @search.try(:[], :property_type)), { class: 'form-control selectpicker show-tick', prompt: 'Todos', :"data-style" => 'btn-primary' }
    / /.col
    .col-md-2
      = label_tag 'Operación'
      = select_tag 'search[transaction_type]', grouped_options_for_select(@transaction_types, @search.try(:[], :transaction_type)), { class: 'form-control selectpicker show-tick', prompt: 'Todos', :'data-style' => 'btn-primary' }
    / /.col
    .col-md-3
      = label_tag 'Barrio'
      = select_tag 'search[neighborhood]', grouped_options_for_select(@neighborhoods, @search.try(:[], :neighborhood)), { class: 'form-control selectpicker show-tick', prompt: 'Todos', :'data-live-search' => :true, :'data-style' => 'btn-primary' }
    / /.col
    .col-md-2
      = label_tag 'Precio'
      = select_tag 'search[price]', grouped_options_for_select(@prices, @search.try(:[], :price)), { class: 'form-control selectpicker show-tick', prompt: 'Todos', :'data-style' => 'btn-primary' }
    / /.col
    .col-md-2
      = label_tag 'Listo?'
      .button
        = submit_tag 'Search', name: nil, class: 'btn btn-primary btn-block'